<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Createdevdbfiles\Module'                        => __DIR__ . '/Module.php',
    'Createdevdbfiles\Controller\IndexController' => __DIR__ . '/src/Createdevdbfiles/Controller/IndexController.php',
    'CreatedevdbfilesTest\Framework\TestCase'        => __DIR__ . '/tests/Createdevdbfiles/Framework/TestCase.php',
    'CreatedevdbfilesTest\SampleTest'                => __DIR__ . '/tests/Createdevdbfiles/SampleTest.php',
);
