<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Contendaa ') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/../../../../../core/public/system/templates/1/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/system/css/style.css')
                        ->prependStylesheet($this->basePath() . '/system/css/login.css')
                        ->prependStylesheet($this->basePath() . '/system/templates/1/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/system/templates/1/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/system/templates/1/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/system/templates/1/js/jquery.min.js')
            ->prependFile($this->basePath() . '/system/templates/1/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/system/templates/1/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body> 
        <?php echo $this->content; ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
